---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: health 
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: health
  template:
    metadata:
      labels:
        app: health
    spec:
      containers:
      - name:  health 
        image: raghudevops28/health:v1
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
...

---
kind: Service
apiVersion: v1
metadata:
  name: health-svc-ext
spec:
  type: LoadBalancer
  selector:
    app: health 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
...
