---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: httpd-deploy 
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd 
        image: raghudevops28/kube-httpd:v1
...

---
kind: Service
apiVersion: v1
metadata:
  name: httpd-svc-ext
spec:
  type: LoadBalancer
  selector:
    app: httpd 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
...
