kind: Pod
apiVersion: v1
metadata:
  name: multipod
spec:
  nodeSelector:
    PURPOSE: DB
  containers:
    - name: mariadb
      image: mariadb
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"

