kind: Pod
apiVersion: v1
metadata:
  name: multipod
spec:
  containers:
    - name: centos
      image: centos
      command: ["sleep"]
      args: ["10000"]
    - name: mariadb
      image: mariadb
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
