apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc 
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: httpd 
        image: raghudevops28/kube-httpd
